spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFDhmfxLojObhVLw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJ/SGUG92B8Uh2hQrz6mf8IxDBXVsNvuR83LVYjEgiTGAH-uQPzZ7VE1nL/aN9IOq5iwZ9iGzw9hAc3y4NyqwWESgE=-i1iPK2^$2_3?pAvS8bj
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTest_SlalomAtlanta_TEST
ADYEN_CLIENT_KEY=test_UZGATJPHRJF3BDXBLWABUJJATYITYE7S
ADYEN_HMAC_KEY=
